[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM8
monitor_port = COM8
lib_deps =
    kosme/arduinoFFT
    https://github.com/pschatzmann/ESP32-A2DP.git
; La librería A2DP es grande — min_spiffs da 1.9 MB para la app
board_build.partitions = min_spiffs.csv
